### ISSUE TITLE
Bug: Upgrade failing on Kubernetes client model attribute

### ISSUE THREAD

**Issue by quixoticmonk** [aws-samples/eks-cluster-upgrade#51]
### Expected Behaviour

Cluster is upgraded and the nodes are updated as required.

### Current Behaviour

Upgrade fails after preflights and cluster upgrade in the node eviction stage. 

```
ERROR:eksupgrade.src.k8s_client:Exception encountered while attempting to drain nodes! Node: ip-*-*-*-*.ec2.internal Cluster: eksup-cluster - Error: module 'kubernetes.client.models' has no attribute 'v1beta1_eviction'
ERROR:eksupgrade.starter:Error encountered during actual update! Exception: Unable to Delete the Node
ERROR:eksupgrade.starter:Exception encountered in main method - Error: Unable to Delete the Node
```

- Reference Kubernetes module installed from the project
```
 pip show kubernetes
Name: kubernetes
Version: 24.2.0
```

### Code snippet

```python
eksupgrade eksup-cluster 1.22 us-east-1
```

### Possible Solution

Update the reference to [v1_eviction](https://github.com/kubernetes-client/python/blob/v24.2.0/kubernetes/client/models/v1_eviction.py
)
- Reference code : https://github.com/aws-samples/eks-cluster-upgrade/blob/main/eksupgrade/src/k8s_client.py#L156
- Reference K8s PR : https://github.com/kubernetes/kubernetes/pull/100724

### Steps to Reproduce

1. Created a cluster using eksctl `eksctl create cluster -f cluster.yaml`. Config yaml below
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksup-cluster
  region: us-east-1
  version: "1.21"
nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
addons: 
- name: vpc-cni
- name: coredns
- name: kube-proxy
```
2.  Installed eksupgrade using `pip install eksupgrade`
3. Ran the eksupgrade command to upgrade the version to 1.22 `eksupgrade eksup-cluster 1.22 us-east-1`

### Amazon EKS upgrade version

0.4.0

### Python runtime version

3.9

### Packaging format used

PyPi

### Debugging logs

```python
Debug logs attached in an earlier section.
```
